# Netlify Configuration File (netlify.toml)

[build]
  command = "npm run build"   # Command to build the project
  publish = "dist"            # Folder to deploy (Vite outputs to 'dist' by default)

[build.environment]
  NODE_VERSION = "18"         # Use Node.js 18 for better compatibility

# Redirects (For Single Page Applications like React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Brotli and Gzip Compression for Faster Load Times
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "br, gzip"

# Security Headers (Protect Against Common Attacks)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Enable Pretty URLs (Removes .html from URLs)
[functions]
  node_bundler = "esbuild"

# Netlify Plugin: Generate Sitemap for SEO
[[plugins]]
  package = "netlify-plugin-sitemap"

  [plugins.inputs]
    buildDir = "dist"            # Folder containing your built files
    siteUrl = "https://nammabhashe.netlify.app/"  